server:
  port: 8999
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: springboot
    key-store-type: PKCS12
    key-alias: tomcat
    trust-store: classpath:keystore.p12
    trust-store-type: PKCS12
    trust-store-password: springboot

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    tls:
      enabled: true
      key-store: classpath:keystore.p12
      key-store-type: PKCS12
      key-password: springboot
      key-store-password: springboot
      trust-store: classpath:keystore.p12
      trust-store-type: PKCS12
      trust-store-password: springboot

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
