server:
  port: 9001
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: springboot
    key-store-type: PKCS12
    key-alias: tomcat
    trust-store: classpath:keystore.p12
    trust-store-type: PKCS12
    trust-store-password: springboot

spring:
  application:
    name: user-service

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    tls:
      enabled: true
      key-store: classpath:keystore.p12
      key-store-type: PKCS12
      key-password: springboot
      key-store-password: springboot
      trust-store: classpath:keystore.p12
      trust-store-type: PKCS12
      trust-store-password: springboot

jwt:
  secret: secretkey123

JWT_TOKEN_VALIDITY: 5*60*60